services:
  - type: web
    name: audia-api
    runtime: python
    repo: https://github.com/miikee183/Audia
    branch: main
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn app.main:app --app-dir backend --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: audia-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: audia-db
    plan: free
    region: virginia
    postgresMajorVersion: 16
